swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Beamline"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
- "http"
paths: 
  /miners: 
    get: 
      tags: 
      - "miners" 
      summary: "Returns a list of available miners"
      description: "" 
      produces: 
      - "application/json" 
      parameters: [] 
      responses: 
        "200": 
          description: "The list of miners" 
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Miner"
  
  /instances:
    get:
      tags:
        - "instances"
      summary: "Returns all instances of miners"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "The list of miner instancens"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/MinerInstance"
      
  /instances/{minerId}:
    post:
      tags: 
        - "instances"
      summary: "Creates a new instance of the specified miner"
      parameters: 
      - name: "minerId" 
        in: "path" 
        description: "The id of the miner" 
        required: true 
        type: "string" 
      - name: "configuration" 
        in: "body" 
        description: "The configuration of the miner instance" 
        required: true
        schema:
          $ref: "#/definitions/MinerInstanceConfiguration"
      responses: 
        "200": 
          description: "OK"
          schema:
            $ref: '#/definitions/MinerInstance'
        "404": 
          description: "Miner not found"
          
  /instances/{instanceId}/delete:
    delete:
      tags:
        - "instances"
      summary: "Terminates and removes a miner instance"
      parameters:
      - name: "instanceId" 
        in: "path" 
        description: "The id of the instanceId" 
        required: true 
        type: "string"
      responses:
        "200":
          description: "Instance succesfully removed"
        "404": 
          description: "Instance not found"
          
  /instances/{instanceId}/start:
    get:
      tags:
        - "instances"
      summary: "Start instance of a miner"
      parameters:
      - name: "instanceId" 
        in: "path" 
        description: "The id of the isntance" 
        required: true 
        type: "string"
      responses:
        "200":
          description: "Instance succesfully started"
          schema:
            type: "boolean"
        "404": 
          description: "Instance not found"
          
  /instances/{instanceId}/stop:
    get:
      tags:
        - "instances"
      summary: "Stop instance of a miner"
      parameters:
      - name: "instanceId" 
        in: "path" 
        description: "The id of the instanceId" 
        required: true 
        type: "string"
      responses:
        "200":
          description: "Instance succesfully stopped"
          schema:
            type: "boolean"
        "404": 
          description: "Instance not found"
  
  /instances/{instanceId}/status:
    get:
      tags:
        - "instances"
      summary: "Checks whether an instance is running"
      parameters:
      - name: "instanceId" 
        in: "path" 
        description: "The id of the instanceId" 
        required: true 
        type: "string"
      responses:
        "200": 
          description: "Whether the instance is running or not" 
          schema:
            $ref: '#/definitions/MinerInstanceStatus'
        "404": 
          description: "Instance not found"
  
        
  /instances/{instanceId}/views:
    post:
      tags:
        - "instances"
      summary: "Get view from miner" 
      parameters:
        - name: "instanceId" 
          in: "path" 
          description: "The id of the miner" 
          required: true 
          type: "string" 
        - name: "configuration" 
          in: "body" 
          description: "The configuration of the miner view" 
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/MinerParameterValue"
      produces:
        - "string" 
      responses: 
        "200": 
          description: "A set of views created by the instance" 
          schema:
              type: "array"
              items:
                $ref: "#/definitions/MinerView"
        "404": 
          description: "Miner not found"
          
  /upload:
     post:
       tags:
        - "utilities"
       summary: "Uploads a file and returns an id"
       responses:
        "200":
          description: "File uploaded correctly and the ID of the file is then returned"
  
  /websockets:
    get:
      tags:
        - "utilities"
      summary: "Reserved for websocket connection"
      responses:
        "200":
          description: "All good"
  
definitions: 
  Stream:
    type: "object"
    properties:
      processName: 
        type: "string"
        description: "The name of the process"
      brokerHost:
        type: "string"
        description: "The hostname of the MQTT-XES broker"
      topicBase:
        type: "string"
        description: "The base topic name used to configure MQTT-XES"

  Miner: 
    type: "object" 
    properties: 
      id: 
        type: "string" 
        description: "A unique id of the miner"
      name:
         type: "string"
         description: "The name of the miner"
      description:
        type: "string"
        description: "A description of the capabilities of the miner"
      configurationParameters:
        type: "array"
        description: "Set of parameters required to configure the miner"
        items:
          $ref: "#/definitions/MinerParameter"
      viewParameters:
        type: "array"
        description: "Set of parameters required to generate a view of the status of the miner"
        items:
          $ref: "#/definitions/MinerParameter"
  
  MinerInstance:
    type: "object"
    properties:
      id:
        type: "string"
        description: "A unique id of the instance of a miner"
      miner: 
        $ref: "#/definitions/Miner"
      configuration:
        $ref: "#/definitions/MinerInstanceConfiguration"
  
  MinerInstanceConfiguration:
    type: "object"
    properties:
      name:
        type: "string"
      stream:
        type: "object"
        $ref: "#/definitions/Stream"
      parameterValues:
        type: "array"
        items:
          $ref: "#/definitions/MinerParameterValue"
  
  MinerInstanceStatus:
    type: "string"
    enum:
      - "mining"
      - "not_mining"
      - "configuring"
  
  MinerParameter:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The name of the parameter"
      type:
        type: "string"
        description: "The type of the parameter"
        enum:
          - "string"
          - "integer"
          - "double"
          - "file"
          - "range_0_1"
      defaultValue:
        type: "string"
        description: "The default value for the parameter"
  
  MinerParameterValue:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The name of the parameter"
      value:
        type: "object"
        description: "The value of the parameter"

  MinerView:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The name of the view"
      value:
        type: "object"
        description: "The content of the view"
      type:
        type: "string"
        description: "The type of view to return"
        enum:
          - "raw"
          - "graphviz"
          - "binary"
          - "google"